### ISSUE TITLE
MessagePack strings get translated during HTTP posts

### ISSUE THREAD

**Issue by thomas07vt** [cheald/manticore#27]
It seems like Manticore/Java is translating body that is getting passed during a POST call. 
I have actually tracked this down to this line:
https://github.com/cheald/manticore/blob/master/lib/manticore/client.rb#L432

If you want to validate, you can do something like this:
```ruby
bytes = []
new_body = StringEntity.new(options[:body], minimum_encoding_for(options[:body]))
byte_array_stream = new_body.get_content
loop { bytes << byte_array_stream.read; break if (byte_array_stream.available <= 0) }

bytes.pack('c*')
```

So maybe its an encoding thing? Should I be force_encoding something other than UTF8?

Here is a sinatra app that shows what I am talking about:

```ruby

require 'sinatra'
require 'manticore'
require 'msgpack'

set :port, 9999

get '/' do

  packed_msg = [{
    :header => {"category"=>"contracts", "X_Trans_Ref"=>"1439578306-17523"},
    :event  => "{\"object\":\"something: else\",\"id\":\"81030443402HMwyAAG\",\"system_timestamp\":\"2015-08-14T18: 51: 43.000Z\"}"
  }].to_msgpack


  # We need to encode as utf-8 or we get this error:
  # Java::JavaNioCharset::UnsupportedCharsetException - ASCII-8BIT
  packed_msg.force_encoding("UTF-8")

  puts "This is th message being sent looks like: \n\n#{packed_msg.inspect}\n\n"

  puts "This is what the unpacked message should look like on the other side:" +
    "\n\n#{MessagePack.unpack(packed_msg).inspect}\n\n"

  opts = {
    headers: { 'content-type'=> 'application/octet-stream' },
    body: packed_msg
  }

  resp = Manticore::Client.new().post('http://localhost:9999/receive', opts).call

  resp.body
end

post '/receive' do
  package = request.body.read

  puts "This is what it actually looks like on the other side:" +
    "\n\n #{package.inspect}\n\n"

  msg = MessagePack.unpack(package)

  puts "And unpacked it looks like this: \n\n#{MessagePack.unpack(package).inspect}\n\n"
  "Done. Please check the console logs."
end

```

**Comment by cheald** [comment]
The super quick fix will be to just pass your own pre-constructed StringEntity via the `entity` option parameter. That way, Manticore won't do anything with it and will just pass it along as-is.

That being said, if you're performing a `force_encoding` then you're saying "I assert that this string contains UTF-8 encoded bytes" - it doesn't actually re-encode things, so if you have ISO-8859-1 data that you are force_encoding to UTF-8, then Manticore is going to say "wait a second, this string contains only ASCII data, we can treat it as ISO-8859-1", because otherwise you have to do a bunch of additional multibyte handling which slows things down.

Can you provide a stack trace for the UnsupportedCharsetException? Is that being thrown from within Manticore, or is that a fix for something else?

**Comment by cheald** [comment]
Okay, after playing with this, you're sending binary data as a StringEntity. This is going to Not Work because binary data shouldn't include an encoding.

Instead, you want to pass a [ByteStringArray](http://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/entity/ByteArrayEntity.html) entity via the `entity` option. 

    java_import "org.apache.http.entity.ByteArrayEntity"
    client.post(..., entity: ByteArrayEntity.new(packed_msg.to_java_bytes))

Manticore should probably be extended to automatically do this when it's passed a body in a binary encoding.

**Comment by cheald** [comment]
That commit detects bodies passed with binary encodings and will automatically wrap them in a ByteArrayEntity, so you don't have to worry about it. As long as the body is in the right string encoding, it should Just Work now.

**Comment by thomas07vt** [comment]
Thanks for the quick turnaround!
