### ISSUE TITLE
client.background should take a block

### ISSUE THREAD

**Issue by andrewvc** [cheald/manticore#32]
Currently if one wants to issue background requests using the builtin executor with callback handlers one must either:

1. Use `#async` which is oriented around a single blocking calling thread making it inherently batch oriented
1. Invoke the executor directly

I propose having `Client#background` taking a block that yields the request object to fill this gap.

I'd be glad to submit a PR later this week if that sounds good to you @cheald

**Comment by cheald** [comment]
Hrm, yeah, I see what you mean. Looking through this, there's an additional bug in that background requests get pushed into the `@async_requests` queue, though I don't think it'll actually manifest as a problem since requests won't actually `#call` more than once.

I think there are two action items here:

1. Make background requests yield the request prior to pushing it to the executor. This makes sense because background requests are handed off immediately.
2. Provide some facility on `Response` for executing it via an executor, so you could do something like:

~~~ruby
response = @client.get("http://github.com").on_success {|resp| ... }
response.background!  # => <Future>
~~~

which would take an arbitrary request (sync, async, whatever) and instead immediately handle it via the background executor. This would permit you to keep all the same request setup procedures as sync calling, but then to pass it to the executor when you're ready to fire it off.

An alternate response would to not immediately queue the background request with the executor, but simply tag it as a background request, so `#call` then pushes it to the executor. This would again let you treat it as identical to other requests.

~~~ruby
response = @client.background.get("http://github.com").on_success {|resp| ... }
response.call # Response is pushed to the executor and is now running, this line won't block
~~~

I like the second approach better in that it preserves the API consistency better, but it is a breaking change; people that are currently using Manticore to fire off background requests would have to explicitly switch to invoking `#call`, or else their requests will simply never get kicked off.

Thoughts?

**Comment by andrewvc** [comment]
@cheald Thanks for the quick response!

I'd rather not break the existing interface. Don't both of the code samples you posted do that? I think simply yielding is good enough for most people. 

Thoughts?

**Comment by cheald** [comment]
Well, *anything* we do here will be some kind of addition or change to the interface. Yields are currently an additional operation. My hesitation with supporting the yield case is that it's semantically different from the other request cases, and I'd like to unify those if possible. Notably, passing a block to `#get` (or whatever) for a sync request binds the block as an `on_success` handler and causes the request to be immediately evaluated, which is kind of the opposite of what passing a block to a background request would do. Ideally, passing a block to a background request would behave similarly.

~~~ruby
client.get(url) {|resp| puts "success!" }             # Blocks, immediately called
client.background.get(url) {|resp| puts "success!" }  # Doesn't block, immediately called
client.async.get(url) {|resp| puts "success!" }       # Doesn't block, is not immediately called, is queued for batch processing
~~~

~~~ruby
client.get(url).on_success {|resp| puts "success!" }             # Returns an unevaluted Response which will be evaluated synchronously
client.background.get(url).on_success {|resp| puts "success!" }  # Returns an unevaluted Response which will be evaluated asynchronously via an executor on #call; functionally equivalent to #async except it doesn't get queued for batch processing
client.async.get(url).on_success {|resp| puts "success!" }       # Returns an unevaluted Response which will be evaluated asynchronously via an executor on #call, or evaluated in parallel on client#execute!
~~~

I think this would be clarified by renaming (or aliasing) `async` to `batch` or `parallel` or something like that, but that would be another interface change. Since Manticore is young, though, I'd like to fix this stuff earlier rather than later - since it's still pre-1.0 I don't have too much of an issue with an interface change with a minor version bump from .4 to .5.

**Comment by cheald** [comment]
So I think the way I want to do this is to make the yield change for the 0.4.x series, and then change the behavior of background requests in the 0.5.x release, so that it behaves like sync/async requests. That patches the immediate issue in a way that's backwards-compatible with the 0.4 series, and fixes the interface issues so we don't accrue tech debt moving forward from 0.5 on. Sound like a decent compromise?

**Comment by cheald** [comment]
819c25e88aa8ce811f0e1790ffcae090939e6639 should address this for the time being. I've also pushed a 0.5.x branch with the more comprehensive changes; I'm not ready to release 0.5.x yet (the new httpcomponents needs some additional testing, and the pool cleanup code needs to be switched to use the new timeout-based expiry it provides), but it should give you a pretty good idea of what I'm thinking WRT unification of the interface. I'd love comments and feedback on it.

**Comment by andrewvc** [comment]
awesome  @cheald that was just what I was looking for :)

I'll try and take a look a little later in the week, but that all sounds like good stuff in the way of improvements!

**Comment by cheald** [comment]
I'm going to go ahead and close this issue for now. Feel free to re-open it if you discover additional issues along these lines.
