### ISSUE TITLE
OAuth integration

### ISSUE THREAD

**Issue by pmashchak** [cheald/manticore#42]
Is it possible to extend builder or request_cofing to do OAuth calls or attach OAuth headers?

**Comment by cheald** [comment]
Extending the client with auto-provided headers is somewhat out of scope for a pure HTTP client; attaching headers to be sent with every request would be a potential security issue, since you could end up sending authorization information to an endpoint that you wouldn't intend to.

Most OAuth libraries handle this for you already; is there something you're wanting to do with Manticore that wouldn't work with the oauth2 gem (which uses Faraday for HTTP, for which Manticore can act as a backend)?

**Comment by pmashchak** [comment]
I need a simple Oauth Authentication based on key and secret with OpenSSL::Digest::SHA1 signature
used simple_oauth gem. But it will be nice if Manticore can include it out of the box.
