### ISSUE TITLE
0.5.6 request

### ISSUE THREAD

**Issue by hobodave** [cheald/manticore#49]
Hi Chris. Would you mind packaging 0.5.6 soon? I'd like to start using the fix from #48 without tying my Gemfile to a SHA.

Thanks!

**Comment by hobodave** [comment]
📟  ping!

**Comment by cheald** [comment]
Sorry! Yeah, let me look at how the dependency stuff ended up.

**Comment by cheald** [comment]
I've released 0.6.0. The minor version bump is because of a change in how dependencies are managed. Rather than using Maven to download and install them, they're vendored in the gem and placed under jar-dependencies management. See the discussion on #47 for context.

Give it a shot and let me know if you have any issues!
